#' Plot a simulated pandemic
#'
#' With this function you can visualize the pandemics you simulated with `sim_pandemic()`.
#'
#' @param pan A pandemic object generated by `sim_pandemic()`
#' @param t Optional: A specific timepoint to plot. If not specified the entire pandemic is plotted over time.
#' @param color A color vector corresponding to Susceptible, Infected, Dead, Recovered.
#' @param sleeptime A time value for the sleep timer for dynamic plotting of the pandemic (do not go below 0.1).
#'
#' @return
#' @export
#'
#' @examples
#'
#' # first simulate a pandemic
#' pandemic = sim_pandemic()
#'
#' # then plot it
#' plot_pandemic(pandemic)
#'
#' # you can also plot individual time points
#' plot_pandemic(pandemic, t = 200)
plot_pandemic = function(pan, t = NULL, color = c("black", "firebrick1", "snow3", "cornflowerblue"), sleeptime = 0.1){

  graphics::par(mfrow = c(1,2), mar = c(5, 3, 4, 2)+0.1)
  sleep = sleeptime

  I = pan$Infected
  S = pan$Susceptible
  R = pan$Recovered
  D = pan$Dead
  K = pan$Susceptible[1]
  n = pan$n
  X = pan$X
  measures = pan$measures

  if(is.null(t)){
    for (i in 1:n){
      plot(I[1:i], type = "l", lwd = 2, ylim = c(0,K),
           xlab = "Time", ylab = "", col = color[2], main = paste("t =", i))
      graphics::lines(S[1:i], lwd = 2)
      graphics::lines(R[1:i], lwd = 2, col = color[3])
      graphics::lines(K-D[1:i], lwd = 2, col = color[4])
      graphics::abline(h = measures*K)

      plot(X[[i]][which(X[[i]][,3]!=4),1], X[[i]][which(X[[i]][,3]!=4),2], pch = 20,
           xlim = c(-5,5), ylim = c(-5,5), xlab = "", ylab = "",
           col = color[X[[i]][which(X[[i]][,3]!=4),3]], main = paste("t =", i),
           xaxt = "n", yaxt = "n")

      Sys.sleep(sleep)
    }
    cat(paste("Deads:",D[n]))
  } else{
    if(length(t) == 1){
      plot(I[1:t], type = "l", lwd = 2, ylim = c(0,K),
           xlab = "Time", ylab = "Infected", col = color[2], main = paste("t =", t))
      graphics::lines(S[1:t], lwd = 2)
      graphics::lines(R[1:t], lwd = 2, col = color[3])
      graphics::lines(K-D[1:t], lwd = 2, col = color[4])
      graphics::abline(h = measures*K)

      plot(X[[t]][which(X[[t]][,3]!=4),1], X[[t]][which(X[[t]][,3]!=4),2], pch = 20,
           xlim = c(-5,5), ylim = c(-5,5), xlab = "", ylab = "",
           col = color[X[[t]][which(X[[t]][,3]!=4),3]], main = paste("t =", t),
           xaxt = "n", yaxt = "n")
    } else{
      warning("If t is specified it must be an integer.")
    }
  }
}
